language: ruby
rvm:
  - 2.6.8
  - 2.7.4
  - 3.0.3
  - 3.1.1
  - jruby-9.1.15.0
gemfile:
  - gemfiles/rails5.gemfile
  - gemfiles/rails6.gemfile
  - gemfiles/rails7.gemfile

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - export BUNDLE_PATH="${TRAVIS_BUILD_DIR}/vendor/bundle"
